WITH Milk AS (
SELECT CART_ID, NAME
FROM CART_PRODUCTS M
WHERE NAME = "Milk"
) SELECT DISTINCT M.CART_ID FROM Milk M
INNER JOIN CART_PRODUCTS C ON C.NAME = "Yogurt"
AND M.CART_ID = C.CART_ID ORDER BY 1